### PR TITLE
Switch from Travis CI to GitHub actions

### PR DESCRIPTION
**Pull request by m4c3**
since the build tests were not running on travis ci lets switch completely to github actions

### CODE REVIEW

**Comment by andyjeffries** [comment]
The only thing that Travis CI gave us that GitHub Actions doesn't (at least as far as I can see, in this iteration) is testing on multiple different Ruby versions - JUUUUST in case one has a weird case.

**Comment by andyjeffries** [comment]
I love the idea though and am so grateful for you doing the legwork, I'm happy to switch, but that worries me.

**Comment by m4c3** [comment]
The tests are running on ruby 2.5, 2.6, 2.7 and 3.0

**Comment by andyjeffries** [comment]
Ohhhh I missed that line! 🎉🎉🎉

Merging then! Thank you 💙

**Pull request merged**
