### PR TITLE
Do not validate when method is delete

### PR DESCRIPTION
**Pull request by kjavier**

### CODE REVIEW

**Comment by andyjeffries** [comment]
I don't know why those two tests fail (Travis), but they don't on my branch. Can you have a look please and ensure the tests still pass and I'll merge this in. Thanks.

**Comment by kjavier** [comment]
@andyjeffries It seems that the failed tests are not related to my commit. When i removed my changes from the file and ran rspec, I still had the same errors. In https://travis-ci.org/flexirest/flexirest/jobs/182210920, the errors are related to not raising TimeoutException.

**Comment by andyjeffries** [comment]
Weird, I try it here and they all pass... Even using the same seed. I'll have a theoretical look at the code, but can't reproduce it.

**Comment by andyjeffries** [comment]
I've trued a few times over the past week, I can't get it to fail locally and the normal master branch passes on Travis, so I'm at a bit of an impasse. Can you get them to fail locally your side?

**Comment by execjosh** [comment]
I believe #65 might take care of the reason for the test failures.

**Comment by andyjeffries** [comment]
Can you rebase off master as #65 is merged now. Then if they all pass I can get this merged in. Thanks.

**Comment by kjavier** [comment]
All checks have passed now. thanks!

**Pull request merged**
