### PR TITLE
Adds proc support to api_auth credentials

### PR DESCRIPTION
**Pull request by davefp**
This matches the proc support for username and password.

### CODE REVIEW

**Comment by davefp** [comment]
Any chance of getting this looked at?

**Comment by andyjeffries** [comment]
Sorry @davefp , completely missed that. Happy with it - merging now. Thanks for the PR.

**Comment by andyjeffries** [comment]
Just pushed out as 1.8.9. Thanks again.

**Comment by davefp** [comment]
Thanks!

**Pull request merged**
