### PR TITLE
Support JSON API

### PR DESCRIPTION
**Pull request by mikevoets**
I added support for JSON API through a proxy. I also extended the README with information on how to activate the proxy and the usage.

I chose to create a new file with a new module dedicated to the proxy, because I felt the `request.rb` file was large enough already. I also created a new spec instead of adding new tests in previous specs for the same reason. Let me know if this was a bad decision.

Lazy loading is the default here unless the response is a compound document (i.e. embedded linked resources). I also implemented an `includes` method that adds an 'include' parameter in the query, to request a compound document if the service supports it. It is used in the same way as the ActiveRecord `includes` method.

Furthermore, I did some bugfixes. For example, it was not possible to define a proxy in a superclass and then inherit it in child classes. Also, in case a `LazyAssociationLoader` only loads a single resource (i.e. not a `ResultIterator`, it failed to populate the `@object` with the attribute values, due to the assumption that the loader always fetches a list of resources. I fixed this with an extra check if the `@object` class is a `Flexirest::Base`, and then yielding keys and values as if it were a hash.

Hope you'll positively consider my pull request. Let me know if you feel something is not rightly done.

### CODE REVIEW

**Comment by mikevoets** [comment]
Please stand-by. I am adding some changes.

**Comment by mikevoets** [comment]
Hmm, this is my first pull request and checks seem to have failed. I don't get much info from the failures though, could you assist me?

**Comment by andyjeffries** [comment]
I've fixed those failures on the master branch (one was a gem update that has happened since the last build where it no longer supports Ruby < 2.0 and the other is an intermittent failure) in commit d4c3753. Please rebase your PR.

**Comment by andyjeffries** [comment]
I love it - thanks for all your hard work, merging now!

**Comment by andyjeffries** [comment]
Released as 1.4.0 - thanks again.

**Comment by adisos** [comment]
Holy shit. It awesome. Good job!

**Pull request merged**
