### PR TITLE
Do not parse multline strings as Date/DateTime

### PR DESCRIPTION
**Pull request by execjosh**
Flexirest matches multiline strings as `Date`/`DateTime` in its attribute parsing.

```ruby
# example.rb
require 'flexirest'

class A
  include Flexirest::AttributeParsing

  def test(val)
    parse_attribute_value(val)
  end
end

[
  %{this\nis\nnot\na\nDate\n2016-07-09\nbut, Flexirest thinks it is!},
  %{this\nis\nnot\na\nDateTime\n2016-07-09T00:00:00.000Z\nbut\nFlexirest thinks it is!},
  %{2016-07-09\n},
  %{\n2016-07-09},
  %{2016-07-09T00:00:00.000Z\n},
  %{\n2016-07-09T00:00:00.000Z},
  %{2016-07-09},
  %{2016-07-09T00:00:00.000Z}
].each do |val|
  p %{#{A.new.test(val).class} -- #{val}}
end
```

```
[flexirest]$ bundle exec ruby example.rb
"Date -- this\nis\nnot\na\nDate\n2016-07-09\nbut, Flexirest thinks it is!"
"DateTime -- this\nis\nnot\na\nDateTime\n2016-07-09T00:00:00.000Z\nbut\nFlexirest thinks it is!"
"Date -- 2016-07-09\n"
"Date -- \n2016-07-09"
"DateTime -- 2016-07-09T00:00:00.000Z\n"
"DateTime -- \n2016-07-09T00:00:00.000Z"
"Date -- 2016-07-09"
"DateTime -- 2016-07-09T00:00:00.000Z"
```

After the fix, the strings will need to be trimmed of newlines...

```
[flexirest]$ bundle exec ruby example.rb
"String -- this\nis\nnot\na\nDate\n2016-07-09\nbut, Flexirest thinks it is!"
"String -- this\nis\nnot\na\nDateTime\n2016-07-09T00:00:00.000Z\nbut\nFlexirest thinks it is!"
"Date -- 2016-07-09\n"
"String -- \n2016-07-09"
"DateTime -- 2016-07-09T00:00:00.000Z\n"
"String -- \n2016-07-09T00:00:00.000Z"
"Date -- 2016-07-09"
"DateTime -- 2016-07-09T00:00:00.000Z"
```

### CODE REVIEW

**Comment by andyjeffries** [comment]
The build needs fixing before we can merge this, other than that, happy to do so.

**Comment by execjosh** [comment]
Wonderful :)  How do you feel about the extra requirement that `\n` to be trimmed?

**Comment by andyjeffries** [comment]
It's all good to me, I agree, trailing newlines should be trimmed, any others should mean it's not a date.

**Comment by execjosh** [comment]
Is there something I can do to help fix the build?  It appears that it is failing to `bundle install` with ruby older than 2.3.x...?

**Comment by execjosh** [comment]
`activesupport requires Ruby version >= 2.2.2`

image

image

**Comment by execjosh** [comment]
Looks like the [master branch is failing][1] in the same way.

[1]: https://travis-ci.org/flexirest/flexirest/builds/142005051

**Comment by execjosh** [comment]
So, I guess options would be:

- Support only activesupport < 5
- Support only activesupport >= 5.0.0
  - Would require culling ruby < 2.2.2
- Allow any activesupport; but, branch based on `RUBY_REVISION`
  - Would necessitate `ext/mkrf_conf.rb` craziness
- Something else?

**Comment by andyjeffries** [comment]
I went with "Allow any activesupport; but, branch based on RUBY_VERSION", but it doesn't need any `ext/mkrf_conf.rb` craziness, just a simple `if` in the .gemspec.  If you rebase off master they should hopefully pass now.

**Comment by execjosh** [comment]
Rebased :thumbsup:

**Pull request merged**
